/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    FormEmpC: typeof import('./src/components/FormEmpC.vue')['default']
    FormEmpD: typeof import('./src/components/FormEmpD.vue')['default']
    FormEmpR: typeof import('./src/components/FormEmpR.vue')['default']
    FormEmpU: typeof import('./src/components/FormEmpU.vue')['default']
    FormInvC: typeof import('./src/components/FormInvC.vue')['default']
    FormInvD: typeof import('./src/components/FormInvD.vue')['default']
    FormInvR: typeof import('./src/components/FormInvR.vue')['default']
    FormInvU: typeof import('./src/components/FormInvU.vue')['default']
    FormPrioC: typeof import('./src/components/FormPrioC.vue')['default']
    FormPrioD: typeof import('./src/components/FormPrioD.vue')['default']
    FormPrioR: typeof import('./src/components/FormPrioR.vue')['default']
    FormPrioU: typeof import('./src/components/FormPrioU.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
